movies = [
    {
        "id": 1,
        "title": "Avatar",
        "overview": "En un exuberante planeta llamado Pandora viven los Na'vi, seres que ...",
        "year": 2009,
        "rating": 7.8,
        "category": "Acción",
    },
    {
        "id": 2,
        "title": "El Padrino",
        "overview": "La historia de la familia mafiosa Corleone durante la década de 1940...",
        "year": 1972,
        "rating": 9.2,
        "category": "Drama",
    },
    {
        "id": 3,
        "title": "Forrest Gump",
        "overview": "La vida de un hombre con un coeficiente intelectual bajo que participa en ...",
        "year": 1994,
        "rating": 8.8,
        "category": "Comedia dramática",
    },
    {
        "id": 4,
        "title": "El Señor de los Anillos: El Retorno del Rey",
        "overview": "La tercera y última entrega de la trilogía de El Señor de los Anillos.",
        "year": 2003,
        "rating": 9.0,
        "category": "Fantasía",
    },
    {
        "id": 5,
        "title": "Jurassic Park",
        "overview": "Un grupo de científicos son invitados a un parque de diversiones donde se ...",
        "year": 1993,
        "rating": 8.1,
        "category": "Ciencia Ficción",
    },
    {
        "id": 6,
        "title": "La La Land",
        "overview": "Dos artistas en Los Ángeles se enamoran mientras intentan alcanzar sus ...",
        "year": 2016,
        "rating": 8.0,
        "category": "Musical",
    },
]
